[김지연] SignUp View 및 serializer 추가
jiyeon-kim-ds/WebRTC-APPLICATION-backend pull request #2
Opened 2022-02-28 08:55 UTC by jiyeon-kim-ds

## 구현 목표
: 회원가입에 사용되는 SignUp View 구현

## 구현 사항 설명
- `User` Model을 사용하는 `SignUpAPIView` 및 `UserSerializer` 구현 
- password의 8자 이상 영문자와 숫자 조건을 확인하는 정규표현식 추가
- 회원가입 성공시 토큰 반환

## 특이사항

2022-02-28 09:16 UTC, jasonkang14 reviewed
완전 깔끔하네요 👍 고생하셨습니다

2022-02-28 09:16 UTC, jasonkang14 commented on users/serializers.py
> +    def create(self, data):
DRF serializer와 Django Manager를 적절히 혼합해서 잘 사용하셨네요 👍

2022-02-28 09:16 UTC, jasonkang14 commented on users/serializers.py
> +            email        = data['email'],
email도 align이 맞으면 좋겠습니다

2022-02-28 09:16 UTC, jasonkang14 commented on users/serializers.py
> +        fields = '__all__'
지금은 괜찮지만 유저정보를 가져올 때도 같은 시리얼라이저를 사용한다면 password에 대한 예외처리가 필요합니다. 이건 그 때가서 고민해보시죠!

2022-02-28 09:16 UTC, jasonkang14 commented on users/views.py
> +        if not re.fullmatch(REGEX_PASSWORD, request.data['password']):
👍

2022-02-28 09:20 UTC, jasonkang14 commented on users/views.py
> +class UserSignUpAPIView(APIView):
테이블에 row를 추가하는거니 [CreateAPIView](https://www.cdrf.co/3.12/rest_framework.generics/CreateAPIView.html)를 사용하는 것이 좋을 것 같습니다!

2022-02-28 09:36 UTC, jiyeon-kim-ds commented on users/serializers.py
> +        fields = '__all__'
네 고민해보겠습니다~!

2022-02-28 09:52 UTC, jasonkang14 requested changes

2022-02-28 09:52 UTC, jasonkang14 commented on users/views.py
> +        if not re.fullmatch(REGEX_PASSWORD, request.data['password']):
`CreateAPIView`의 [post method](https://www.cdrf.co/3.9/rest_framework.generics/CreateAPIView.html#post)는 `self.create()`를 호출합니다. 

그리고 [create method는](https://www.cdrf.co/3.9/rest_framework.generics/CreateAPIView.html#create) 라는 기능이 있는데요, 참고하시면 조금 더 DRF를 활용하는 코드로 작성이 가능할 것 같습니다.

2022-03-01 06:32 UTC, jiyeon-kim-ds commented on users/views.py
> +class UserSignUpAPIView(APIView):
@jasonkang14 병진님 CreateAPIView를 이용해 view 코드를 간단히 했습니다~! 감사합니다!

2022-03-01 06:39 UTC, jasonkang14 commented on users/views.py
> +class UserSignUpAPIView(APIView):
깔끔하네요 👍

2022-03-01 06:39 UTC, jasonkang14 commented
LGTM

2022-03-01 06:40 UTC, merged